#!/usr/bin/php
<?php

require_once __DIR__ . '/vendor/autoload.php';

# Required environment variables
$variables = [
    "TYPESENSE_API_KEY",
    "TYPESENSE_HOST",
    "TYPESENSE_PORT",
    "TYPESENSE_PROTOCOL",
    "REACHMEE_HELSINGBORG_PATH",
    "REACHMEE_INTRANAT_HELSINGBORG_PATH",
    "WP_EVENTS_API_URL",
    "WORDPRESS_EXHIBITION_EVENT_PATH",
    "ELEMENTARY_SCHOOL_API_URL",
    "PRE_SCHOOL_API_URL",
    "WP_LEGACY_EVENTS_API_URL",
    "AXIELL_EVENTS_URL",
    "TIX_EVENTS_API_URL",
    "STRATSYS_INNOVATION_PATH",
    "STRATSYS_INNOVATION_AUTH",
    "STRATSYS_INNOVATION_CLIENTID",
    "STRATSYS_INNOVATION_CLIENTSECRET",
];

# Check if each required environment variable is set
$missing_variables = [];

foreach ($variables as $var) {
    if (empty(getenv($var))) {
        $missing_variables[] = $var;
    }
}

if (count($missing_variables) > 0) {
    echo "Error: The following environment variables are not set:\n";
    foreach ($missing_variables as $var) {
        echo " - $var\n";
    }
    exit(1);
}

// Ensure that the Typesense client can connect to the server
try{
    $typesenseClient = new \Typesense\Client([ 'nodes' => [ [ 'host' => getenv('TYPESENSE_HOST'), 'port' => (int)getenv('TYPESENSE_PORT'), 'protocol' => getenv('TYPESENSE_PROTOCOL'), ], ], 'api_key' => getenv('TYPESENSE_API_KEY'), ]);
    $typesenseClient->health->retrieve();
} catch(Exception $e) {
    echo "Error: Unable to connect to Typesense server. Please check your Typesense configuration.\n";
    exit(1);
}