#!/usr/bin/php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use SchemaTransformer\IO\V2\HttpReader;
use SchemaTransformer\Loggers\TerminalLogger;
use SchemaTransformer\Paginators\WordpressPaginator;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseCollection;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseStorage;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseStorageConfig;
use SchemaTransformer\Transforms\School\ElementarySchool\ElementarySchoolTransform;

$id = 'ElementarySchool';
$httpReaderPath = getenv('ELEMENTARY_SCHOOL_API_URL');
$typesenseCollection = TypesenseCollection::ElementarySchool;
$typesenseCollectionClearFilter = [ 'filter_by' => 'x-created-by:=municipio%3A%2F%2Fschema.org-transformer%2Fwp-headless' ];
$typesenseClient = new \Typesense\Client([ 'nodes' => [ [ 'host' => getenv('TYPESENSE_HOST'), 'port' => (int)getenv('TYPESENSE_PORT'), 'protocol' => getenv('TYPESENSE_PROTOCOL'), ], ], 'api_key' => getenv('TYPESENSE_API_KEY'), ]);
$transformer = new ElementarySchoolTransform('R', $typesenseClient);

$logger = new TerminalLogger($id);
$storageConfig = new TypesenseStorageConfig( $typesenseClient, $typesenseCollection, $typesenseCollectionClearFilter );
$reader = new HttpReader( $httpReaderPath, $transformer, [ 'Content-Type' => 'application/json', 'Accept' => 'application/json', ], new WordpressPaginator(), $logger );
$storage = new TypesenseStorage($storageConfig, $logger);
$storage->store($reader->read());
