#!/usr/bin/php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use SchemaTransformer\IO\V2\HttpReader;
use SchemaTransformer\Loggers\TerminalLogger;
use SchemaTransformer\Paginators\WordpressPaginator;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseCollection;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseStorage;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseStorageConfig;
use SchemaTransformer\Transforms\WPExhibitionEventTransform;

$id = 'ExhibitionEvent';
$logger = new TerminalLogger($id);
$lockRunner = new \SchemaTransformer\LockRunner\LockRunner($id, $logger);

if(!$lockRunner->lock()) {
    return;
}

$httpReaderPath = getenv('WORDPRESS_EXHIBITION_EVENT_PATH');
$typesenseCollection = TypesenseCollection::ExhibitionEvent;
$typesenseCollectionClearFilter = [ 'filter_by' => '@type:ExhibitionEvent', ];
$transformer = new WPExhibitionEventTransform();
$typesenseClient = new \Typesense\Client([ 'nodes' => [ [ 'host' => getenv('TYPESENSE_HOST'), 'port' => (int)getenv('TYPESENSE_PORT'), 'protocol' => getenv('TYPESENSE_PROTOCOL'), ], ], 'api_key' => getenv('TYPESENSE_API_KEY'), ]);
$storageConfig = new TypesenseStorageConfig( $typesenseClient, $typesenseCollection, $typesenseCollectionClearFilter );
$reader = new HttpReader( $httpReaderPath, $transformer, [ 'Content-Type' => 'application/json', 'Accept' => 'application/json', ], new WordpressPaginator(), $logger );
$storage = new TypesenseStorage($storageConfig, $logger);
$storage->store($reader->read());
