#!/usr/bin/php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use SchemaTransformer\IO\V2\HttpReader;
use SchemaTransformer\Loggers\TerminalLogger;
use SchemaTransformer\Paginators\WordpressPaginator;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseCollection;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseStorage;
use SchemaTransformer\Storage\TypesenseStorage\TypesenseStorageConfig;
use SchemaTransformer\Transforms\School\PreSchool\PreSchoolTransform;
use SchemaTransformer\Webhooks\Webhooks;

$id = 'PreSchool';
$logger = new TerminalLogger($id);
$lockRunner = new \SchemaTransformer\LockRunner\LockRunner($id, $logger);

if(!$lockRunner->lock()) {
    return;
}

$httpReaderPath = getenv('PRE_SCHOOL_API_URL');
$typesenseCollection = TypesenseCollection::PreSchool;
$typesenseCollectionClearFilter = [ 'filter_by' => '@type:=PreSchool' ];
$typesenseClient = new \Typesense\Client([ 'nodes' => [ [ 'host' => getenv('TYPESENSE_HOST'), 'port' => (int)getenv('TYPESENSE_PORT'), 'protocol' => getenv('TYPESENSE_PROTOCOL'), ], ], 'api_key' => getenv('TYPESENSE_API_KEY'), ]);
$transformer = new PreSchoolTransform('R', $typesenseClient);
$storageConfig = new TypesenseStorageConfig( $typesenseClient, $typesenseCollection, $typesenseCollectionClearFilter );
$reader = new HttpReader( $httpReaderPath, $transformer, [ 'Content-Type' => 'application/json', 'Accept' => 'application/json', ], new WordpressPaginator(), $logger );
$storage = new TypesenseStorage($storageConfig, $logger);
$storage->store($reader->read());

if( getenv('PRE_SCHOOL_MONITOR_URL') ) {
    (new Webhooks())->trigger(getenv('PRE_SCHOOL_MONITOR_URL'));
}